### ISSUE TITLE
A minor typo (maybe)

### ISSUE THREAD

**Issue by meShakti** [GoogleCloudPlatform/appengine-guestbook-python#15]
I am a beginner at python so don't know for sure if its a typo or not .
In code of guestbook.py
application = webapp2.WSGIApplication([
    ('/', MainPage),
    ('/sign', Guestbook),
], debug=True)

Didn't it look it has extra comma after Guestbook.

**Comment by gainward** [comment]
Nope, this is fine. A trailing comma is optional in these situations, but can make the diff look nicer when elements are added or removed from the list.
