### ISSUE TITLE
internal server error

### ISSUE THREAD

**Issue by samsammurphy** [GoogleCloudPlatform/appengine-guestbook-python#38]
I want to be friends with app engine but so far no luck. please help.

This is the error message

![internal_server_error](https://user-images.githubusercontent.com/16657983/28199558-4dcdb702-6802-11e7-842a-0c711b672157.png)

This is the input used to generate that message

![command_line](https://user-images.githubusercontent.com/16657983/28199563-51db5750-6802-11e7-9980-6eb60e66d6f7.png)

**Comment by samsammurphy** [comment]
p.s. this is where I got up to with the e2e test 

![e2e_test](https://user-images.githubusercontent.com/16657983/28199643-f029d850-6802-11e7-879b-f5fe02089fac.png)

**Comment by jonparrott** [comment]
Hey @samsammurphy, you should be able to fix this by running `gcloud app deploy index.yaml` to update the datastore indexes. It'll take a few minutes for them to start serving. Let me know if you run into anything else.
