### ISSUE TITLE
Internal Server Error The server has either erred or is incapable of performing the requested operation.

### ISSUE THREAD

**Issue by city535353** [GoogleCloudPlatform/appengine-guestbook-python#40]
When I upload to GAE, and test it with URL. The error is:
NeedIndexError: no matching index found. recommended index is:
- kind: Greeting
  ancestor: yes
  properties:
  - name: date
    direction: desc

The suggested index for this query is:
- kind: Greeting
  ancestor: yes
  properties:
  - name: date
    direction: desc

**Comment by narenchoudhary** [comment]
This issue seems to be a duplicate of #38 .

**Comment by flik** [comment]
same issue with me and fixed with : gcloud app deploy app.yaml 
It should be update in google document https://cloud.google.com/shell/docs/quickstart

**Comment by meredithslota** [comment]
https://cloud.google.com/shell/docs/deploy-app-engine-app has been updated.
